#!/bin/bash

clear

read -p "Enter your commit message: " my_message

echo ". . . Giving user permission to execute files . . . "
chmod u+x *

echo ". . . Now uploading Changes . . ."
git add .
git commit -m "${my_message}"
git push


echo ". . . Your changes have been pushed successfully . . ."
